### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by Catofes** [lordfriend/Albireo#16]
https://suki.moe/#/play/e8a305e8-044c-40ec-80bf-0ed87712eb60

Stdout:
2016-06-11 16:51:43+0000 [-] "172.17.0.1" - - [11/Jun/2016:16:51:42 +0000] "GET /api/home/episode/e8a305e8-044c-40ec-80bf-0ed87712eb60 HTTP/1.0" 500 291 "https://suki.moe/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

StdErr:

```
2016/06/11 16:51:43 app:1423 Exception on /api/home/episode/e8a305e8-044c-40ec-80bf-0ed87712eb60 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/home/herbertqiao/Albireo/routes/home.py", line 35, in episode_detail
    return bangumi_service.episode_detail(episode_id)
  File "/home/herbertqiao/Albireo/service/bangumi.py", line 73, in episode_detail
    raise error
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-5: ordinal not in range(128)
```

**Comment by Catofes** [comment]
service/common.py

```
    def generate_video_link(self, bangumi_id, path):
        video_link = '/video/{0}/{1}'.format(bangumi_id, path.encode('utf-8'))
        if self.video_domain is not None:
            video_link = self.video_domain + video_link
        return video_link

```
use encode('utf-8') solved the bug. No idea why.

**Comment by lordfriend** [comment]
Pull Request for this solution is welcomed

**Comment by lordfriend** [comment]
The fix code is removed by some reason and this issue is back to life again. So need fix now
